sudo: required
language: node_js
node_js:
  - 10
  - 12
  
services:
  - docker

env:
  COMPOSE_VERSION: 1.21.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker network create messaging
  - docker-compose build
  - docker-compose run messaging npm install
  - docker-compose run messaging yarn
  - docker-compose run messaging yarn lint
  - docker-compose run messaging yarn test
